### ISSUE TITLE
Reponses are opening in modal in production

### ISSUE THREAD

**Issue by merijnponzo** [boxybird/inertia-wordpress#10]
Hi there, 

Somehow cached responses are showed in a modal.
When i activate SpinupWP (nginx caching plugin from my wordpress hosting environment) or cache-enabler, strange things happens. Some windows / links are opening in a modal, some not.

As Reinink says in #https://github.com/inertiajs/inertia/issues/586
```
This is what happens when you don't return an Inertia response from the <inertia-link> endpoint. All Inertia requests MUST return an Inertia response, otherwise they are shown in a modal like this. This is core to how the library works. 👍
```
When Logged in the no-cache is added to the headers, no modal is opened 
I thought maybe the 'no-cache, must-revalidate, max-age=0' 

Has this todo with the inertia-wordpress adapter or is this default inertia behaviour?

**Comment by boxybird** [comment]
Hello!

"Has this todo with the inertia-wordpress adapter or is this default inertia behaviour?" Both.

The short answer: Using an out-of-the-box WordPress caching solution will most likely not work with Inertia.

The error/debug modal you're seeing is because the returned response from the `<inertia-link>` click is not in the correct payload format Inertia is looking for on the client. See https://inertiajs.com/the-protocol#the-page-object

When you call and pass data to the `Inertia::render(...)` method in WP, these lines formats the response payload correctly so the Inertia client adapter knows how to handle the data: https://github.com/boxybird/inertia-wordpress/blob/ccd1259fe2fb144cba59b32ed32f0cb8acfe8eb9/src/Inertia.php#L33-L44

My guess is the caching layer/solution you're using is just passing back a raw, cached HTML response and not a proper Inertia response. Hence the error modal.

This doesn't mean a caching solution is not possible, it just has to be done at the data level and not the response level.

Silly example:

```php
<?php

use BoxyBird\Inertia\Inertia;

$posts = get_transient('cached_posts');

if (!$posts) {
    $posts = set_transient('cached_posts', get_posts(), 3600);
}

return Inertia::render('Blog', [
    'posts' => $posts,
]);
```

**Comment by merijnponzo** [comment]
Hi, okey but even without caching plugins, clicking on the logo (at home)
https://dammes.ponzoblocks.nl. Still gives me the whole site within a modal. Or clicking on 'about', after a second time it fires within the modal.

So reading the how it works part:
Once an Inertia app has been booted, all subsequent requests to the site are made via XHR with a special X-Inertia header set to true. This header indicates that the request is being made by Inertia, and isn't a standard full-page visit.

I see that X-Inertia: true is within the response header, but still it's shown within a modal.

Raw headers that giving me a modal response:


Request:
```
XHRGET https://dammes.ponzoblocks.nl/
[HTTP/2 200 OK 21ms]

GET
https://dammes.ponzoblocks.nl/
Status200
OK
VersionHTTP/2
Transferred5.88 kB (65.28 kB size)
Referrer Policystrict-origin-when-cross-origin
HTTP/2 200 OK
server: nginx
date: Mon, 03 May 2021 09:16:17 GMT
content-type: text/html; charset=UTF-8
vary: Accept-Encoding
link: <https://dammes.ponzoblocks.nl/>; rel=shortlink
x-frame-options: SAMEORIGIN
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
fastcgi-cache: HIT
strict-transport-security: max-age=31536000; includeSubDomains
content-encoding: gzip
X-Firefox-Spdy: h2    	
GET / HTTP/2
Host: dammes.ponzoblocks.nl
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:88.0) Gecko/20100101 Firefox/88.0
Accept: text/html, application/xhtml+xml
Accept-Language: en-GB,en;q=0.5
Accept-Encoding: gzip, deflate, br
X-Requested-With: XMLHttpRequest
X-Inertia: true
Content-Type: application/json;charset=utf-8
DNT: 1
Connection: keep-alive
Referer: https://dammes.ponzoblocks.nl/
TE: Trailers
```

response:
```
XHRGEThttps://dammes.ponzoblocks.nl/
[HTTP/2 200 OK 21ms]
GET
https://dammes.ponzoblocks.nl/
Status200
OK
VersionHTTP/2
Transferred5.88 kB (65.28 kB size)
Referrer Policystrict-origin-when-cross-origin
HTTP/2 200 OK
server: nginx
date: Mon, 03 May 2021 09:16:17 GMT
content-type: text/html; charset=UTF-8
vary: Accept-Encoding
link: <https://dammes.ponzoblocks.nl/>; rel=shortlink
x-frame-options: SAMEORIGIN
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
fastcgi-cache: HIT
strict-transport-security: max-age=31536000; includeSubDomains
content-encoding: gzip
X-Firefox-Spdy: h2
GET / HTTP/2
Host: dammes.ponzoblocks.nl
User-Agent: Mozilla/5.0 Gecko/20100101 Firefox/88.0
Accept: text/html, application/xhtml+xml
Accept-Language: en-GB,en;q=0.5
Accept-Encoding: gzip, deflate, br
X-Requested-With: XMLHttpRequest
X-Inertia: true
Content-Type: application/json;charset=utf-8
DNT: 1
Connection: keep-alive
Referer: https://dammes.ponzoblocks.nl/
TE: Trailers
```

**Comment by merijnponzo** [comment]
Okay, It appears that spinupwp (my hosting enviroment) has antother toggle 'disable page cache', besides the plugin.
https://spinupwp.com/doc/customizing-page-cache-exclusions/

It is possible that the Fastcgi-Cache header not works well with inertia

**Comment by boxybird** [comment]
To be honest, I'm not sure. It's not a tech I use.

But my understanding of Inertia is as long as the request/response protocol is correct, all should be good. Based on your screenshot above, the response headers look fine. My GUESS is the cached payload in the response is incorrect.

That's said, I'm closing as it seems this issue is more of an individual environment problem.

**Comment by patlamontagne** [comment]
Might be a good idea to test if PR https://github.com/boxybird/inertia-wordpress/pull/12 fixes this issue.

**Comment by suman98** [comment]
Any one is this issue fixed ??? I am still stuck in 2022.

**Comment by merijnponzo** [comment]
I stopped using inertia since it was causing so many troubles

My current setup for months with i am very happy with:

Use template tags properties just like vue:
https://github.com/timber/timber

Use smooth page transitions:
https://highway.js.org/

Create interactive page components without a blink
https://alpinejs.dev/

+ Straight and forward setup
+ No problems with SEO
+ No problems with caching your pages

Just fun, have fun!

**Comment by boxybird** [comment]
@suman98 The challenge with troubleshooting "responses are opening in modal" type issues is that's the default/intended behavior to display any Inertia error. 

Can you share your exact error?

If you're having the same problem @merijnponzo had, it looks like he's found an alternative tech stack he likes. 


> I stopped using inertia since it was causing so many troubles
> 
> My current setup for months with i am very happy with:
> 
> Use template tags properties just like vue: https://github.com/timber/timber
> 
> Use smooth page transitions: https://highway.js.org/
> 
> Create interactive page components without a blink https://alpinejs.dev/
> 
> * Straight and forward setup
> * No problems with SEO
> * No problems with caching your pages
> 
> Just fun, have fun!

**Comment by boxybird** [comment]
@suman98 Thanks for the steps! But I can't seem to duplicate the error. I'm testing your thoughts using the demo site I created: https://wp-inertia.andrewrhyand.com/

"If page loads with disk cache...". Are you still adding a custom (SpinupWP caching plugin) caching layer/solution above and beyond the browser defaults? If so, can you share the network tab?

Are you able to replicate the error on my site? If so, can you provide a screenshot? 

With default caching enabled this is what I see. No issues:
![image](https://user-images.githubusercontent.com/18317878/150386235-e9fc6723-dea0-4391-983f-2c10a66464aa.png)

**Comment by suman98** [comment]
@boxybird I noticed that `https://wp-inertia.andrewrhyand.com/movies` is not loaded from disk cache so its not showing in popup model but in my site  every thing loads from disk cache after first request. like the  attached  image below. Maybe this issue can be resolved if we add extra parameter in xhr request of inertia like `/someurl?initiator=inertia`. Any way  for God's sake can you please suggest me some solution for this issue without changing server configuration ?
![Screenshot from 2022-01-21 08-49-45](https://user-images.githubusercontent.com/41943773/150459540-7d57f1b6-0485-4cb2-b7bb-14bf8179900f.jpg)

**Comment by boxybird** [comment]
@suman98 I found the reason why it's failing with "disk cache" (which basically is page caching).

The short answer is you can't use full page caching with Inertia as there are no HTTP Request Headers being sent to the server to tell Inertia how to handle the response.

Which makes sense, it's a cached paged. No Request is being made.

![image](https://user-images.githubusercontent.com/18317878/150575583-32a08bdc-5a55-43ab-9bbb-5cc7488362bf.png)
![image](https://user-images.githubusercontent.com/18317878/150575731-d25093b1-d7b7-420d-92cb-28af0d2bc1c4.png)


However, Inertia::render() NEEDS those Request Headers on every request to determine what type of payload to send back to client.
```php
public static function render(string $component, array $props = [])
{
    global $bb_inertia_page;

    self::setRequest();

    self::setUrl();
    self::setComponent($component);
    self::setProps($props);

    $bb_inertia_page = [
        'url'       => self::$url,
        'props'     => self::$props,
        'version'   => self::$version,
        'component' => self::$component,
    ];

    /**
     * If Inertia XHR/AJAX headers ARE detected in the request. Send $bb_inertia_page data as a JSON response.
     *
     * And add these headers to let the Inertia client know
     * that we're sending JSON specifically for Inertia to use.
     *
     * header('Vary: Accept');
     * header('X-Inertia: true');
     */
    if (InertiaHeaders::inRequest()) {
        InertiaHeaders::addToResponse();

        // Note: wp_send_json() kills the script execution. So any code below is not executed.
        wp_send_json($bb_inertia_page);
    }

    /**
     * If Inertia XHR/AJAX headers NOT detected in the request. Render the PHP page template
     * and hydrate the <div> found in the bb_inject_inertia() function with the $bb_inertia_page data.
     */
    require_once get_stylesheet_directory() . '/' . self::$root_view;
}
```

The reason we get the modal popup is the Inertia client did not detect proper Response Headers (because they were never sent), so it throw an error modal showing us what was returned. In this case, is the cached HTML page.

**Comment by patlamontagne** [comment]
Hi @suman98 

Like @boxybird said, this is expected behavior from inertia itself. If you can't change your server configuration,  there might be ways to bypass your server caching.

I looked up [SpinupWP's doc on caching](https://spinupwp.com/doc/caching-in-spinupwp/#page-caching) since it was being specifically named in this issue, and it says  `By default, any POST requests or URLs containing query string parameters bypass the page cache` so in this case, manually adding a cache-busting GET parameters to your inertia links should work with the default configuration.

However looking at your previous screenshots, looks like your urls with parameters *are* being cached so I'm assuming you're using another caching solution that can't be bypassed this way.
